platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'IFLYADLibSimple' do
use_frameworks!

pod 'IFLYADLib'

#pod 'Ads-CN-Beta','6.7.0.3', :subspecs => ['BUAdSDK', 'CSJMediation']

end
